[package]
name = "limpa_downloads"
version = "0.5.0"
edition = "2021"
license = "mit"

[dependencies]
pancurses = "0.17.0"

[target.'cfg(debug_assertions)'.dependencies]
sysinfo = "0.29.8"
utilitarios = { path="../rust-utilitarios/" }

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

